name: Aruna Test

on:
  workflow_dispatch:

jobs:
  node:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Build Node
        run: cargo build -p aruna-node

      - name: Start Node
        run: timeout 15s cargo run -p aruna-node
